# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b5f899ab84131a76c6b5ba691cbdd3a16d1cc4e14774538e18a37178ecfa2cec99358d49b31f08f8162b0485c2d41502c072397dfa43da1a7e8819d644328203

test:
  secret_key_base: ccf23e3ed6a2947a711c8c47c4e4ac834697abcd6902750ce5bef148e469a9b03d5e9eb8a8db0df8fd757b324e1d24a4a62accdc4129281f4725c571faefe77c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
